#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLy_filehosonhansu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLy_filehoso")]
	public partial class QLy_filehosonhansuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNS_FILE_HOSO(NS_FILE_HOSO instance);
    partial void UpdateNS_FILE_HOSO(NS_FILE_HOSO instance);
    partial void DeleteNS_FILE_HOSO(NS_FILE_HOSO instance);
    partial void InsertNS_HOSONHANSU(NS_HOSONHANSU instance);
    partial void UpdateNS_HOSONHANSU(NS_HOSONHANSU instance);
    partial void DeleteNS_HOSONHANSU(NS_HOSONHANSU instance);
    #endregion
		
		public QLy_filehosonhansuDataContext() : 
				base(global::QLy_filehosonhansu.Properties.Settings.Default.QLy_filehosoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLy_filehosonhansuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLy_filehosonhansuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLy_filehosonhansuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLy_filehosonhansuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NS_FILE_HOSO> NS_FILE_HOSOs
		{
			get
			{
				return this.GetTable<NS_FILE_HOSO>();
			}
		}
		
		public System.Data.Linq.Table<NS_HOSONHANSU> NS_HOSONHANSUs
		{
			get
			{
				return this.GetTable<NS_HOSONHANSU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NS_FILE_HOSO")]
	public partial class NS_FILE_HOSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _STT;
		
		private int _IDHOSONHANSU;
		
		private string _TenFile;
		
		private string _DuongDan;
		
		private string _DungLuong;
		
		private string _KieuFile;
		
		private EntityRef<NS_HOSONHANSU> _NS_HOSONHANSU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnIDHOSONHANSUChanging(int value);
    partial void OnIDHOSONHANSUChanged();
    partial void OnTenFileChanging(string value);
    partial void OnTenFileChanged();
    partial void OnDuongDanChanging(string value);
    partial void OnDuongDanChanged();
    partial void OnDungLuongChanging(string value);
    partial void OnDungLuongChanged();
    partial void OnKieuFileChanging(string value);
    partial void OnKieuFileChanged();
    #endregion
		
		public NS_FILE_HOSO()
		{
			this._NS_HOSONHANSU = default(EntityRef<NS_HOSONHANSU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHOSONHANSU", DbType="Int NOT NULL")]
		public int IDHOSONHANSU
		{
			get
			{
				return this._IDHOSONHANSU;
			}
			set
			{
				if ((this._IDHOSONHANSU != value))
				{
					if (this._NS_HOSONHANSU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHOSONHANSUChanging(value);
					this.SendPropertyChanging();
					this._IDHOSONHANSU = value;
					this.SendPropertyChanged("IDHOSONHANSU");
					this.OnIDHOSONHANSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenFile", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenFile
		{
			get
			{
				return this._TenFile;
			}
			set
			{
				if ((this._TenFile != value))
				{
					this.OnTenFileChanging(value);
					this.SendPropertyChanging();
					this._TenFile = value;
					this.SendPropertyChanged("TenFile");
					this.OnTenFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDan", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DuongDan
		{
			get
			{
				return this._DuongDan;
			}
			set
			{
				if ((this._DuongDan != value))
				{
					this.OnDuongDanChanging(value);
					this.SendPropertyChanging();
					this._DuongDan = value;
					this.SendPropertyChanged("DuongDan");
					this.OnDuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DungLuong
		{
			get
			{
				return this._DungLuong;
			}
			set
			{
				if ((this._DungLuong != value))
				{
					this.OnDungLuongChanging(value);
					this.SendPropertyChanging();
					this._DungLuong = value;
					this.SendPropertyChanged("DungLuong");
					this.OnDungLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KieuFile", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KieuFile
		{
			get
			{
				return this._KieuFile;
			}
			set
			{
				if ((this._KieuFile != value))
				{
					this.OnKieuFileChanging(value);
					this.SendPropertyChanging();
					this._KieuFile = value;
					this.SendPropertyChanged("KieuFile");
					this.OnKieuFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NS_HOSONHANSU_NS_FILE_HOSO", Storage="_NS_HOSONHANSU", ThisKey="IDHOSONHANSU", OtherKey="ID", IsForeignKey=true)]
		public NS_HOSONHANSU NS_HOSONHANSU
		{
			get
			{
				return this._NS_HOSONHANSU.Entity;
			}
			set
			{
				NS_HOSONHANSU previousValue = this._NS_HOSONHANSU.Entity;
				if (((previousValue != value) 
							|| (this._NS_HOSONHANSU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NS_HOSONHANSU.Entity = null;
						previousValue.NS_FILE_HOSOs.Remove(this);
					}
					this._NS_HOSONHANSU.Entity = value;
					if ((value != null))
					{
						value.NS_FILE_HOSOs.Add(this);
						this._IDHOSONHANSU = value.ID;
					}
					else
					{
						this._IDHOSONHANSU = default(int);
					}
					this.SendPropertyChanged("NS_HOSONHANSU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NS_HOSONHANSU")]
	public partial class NS_HOSONHANSU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaNS;
		
		private string _HovaTen;
		
		private System.DateTime _NgaySinh;
		
		private string _SoCMND;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private EntitySet<NS_FILE_HOSO> _NS_FILE_HOSOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaNSChanging(string value);
    partial void OnMaNSChanged();
    partial void OnHovaTenChanging(string value);
    partial void OnHovaTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public NS_HOSONHANSU()
		{
			this._NS_FILE_HOSOs = new EntitySet<NS_FILE_HOSO>(new Action<NS_FILE_HOSO>(this.attach_NS_FILE_HOSOs), new Action<NS_FILE_HOSO>(this.detach_NS_FILE_HOSOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MaNS
		{
			get
			{
				return this._MaNS;
			}
			set
			{
				if ((this._MaNS != value))
				{
					this.OnMaNSChanging(value);
					this.SendPropertyChanging();
					this._MaNS = value;
					this.SendPropertyChanged("MaNS");
					this.OnMaNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HovaTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HovaTen
		{
			get
			{
				return this._HovaTen;
			}
			set
			{
				if ((this._HovaTen != value))
				{
					this.OnHovaTenChanging(value);
					this.SendPropertyChanging();
					this._HovaTen = value;
					this.SendPropertyChanged("HovaTen");
					this.OnHovaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="VarChar(100)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(100)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NS_HOSONHANSU_NS_FILE_HOSO", Storage="_NS_FILE_HOSOs", ThisKey="ID", OtherKey="IDHOSONHANSU")]
		public EntitySet<NS_FILE_HOSO> NS_FILE_HOSOs
		{
			get
			{
				return this._NS_FILE_HOSOs;
			}
			set
			{
				this._NS_FILE_HOSOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NS_FILE_HOSOs(NS_FILE_HOSO entity)
		{
			this.SendPropertyChanging();
			entity.NS_HOSONHANSU = this;
		}
		
		private void detach_NS_FILE_HOSOs(NS_FILE_HOSO entity)
		{
			this.SendPropertyChanging();
			entity.NS_HOSONHANSU = null;
		}
	}
}
#pragma warning restore 1591
